services:
  referral_db:
    container_name: referral_db
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_codes:
    container_name: redis_codes
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    container_name: referral_api
    build: .
    restart: always
    depends_on:
      - referral_db
      - redis_codes
      - db_migration
    ports:
      - "5001:5000"
    command: ["gunicorn", "-w", "2", "--worker-class", "gevent", "--max-requests", "1000", "--max-requests-jitter", "50", "-b", "0.0.0.0:5001", "wsgi:app"]
    volumes:
      - ./app.log:/app/app.log

  celery_worker:
    container_name: referral_celery
    build: .
    restart: always
    depends_on:
      - referral_db
      - redis_codes
    command: ["celery", "-A", "app.app_factory.celery", "worker", "--loglevel=info"]

  db_migration:
    build: .
    container_name: db_migration
    depends_on:
      - referral_db
    command: >
      bash -c "flask db upgrade"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - TZ=Europe/Moscow

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"

volumes:
  postgres_data:
  redis_data:
  grafana_data: