services:
  db_curs:
    container_name: referral_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=referral_db
    image: postgres:14.3-alpine
  redis_codes:
    container_name: redis_codes
    ports:
      - "6379:6379"
    image: redis:7.2