services:
  db_curs:
    container_name: referral_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=referral_db
    image: postgres:14.3-alpine