"""fix set

Revision ID: 0037ef843d78
Revises: b6f85125263d
Create Date: 2025-05-28 05:17:41.203669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0037ef843d78'
down_revision = 'b6f85125263d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_column('sets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
